// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: pusher.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PusherEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//	*PusherEvent_Client
	//	*PusherEvent_Server
	Event isPusherEvent_Event `protobuf_oneof:"event"`
}

func (x *PusherEvent) Reset() {
	*x = PusherEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pusher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PusherEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PusherEvent) ProtoMessage() {}

func (x *PusherEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pusher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PusherEvent.ProtoReflect.Descriptor instead.
func (*PusherEvent) Descriptor() ([]byte, []int) {
	return file_pusher_proto_rawDescGZIP(), []int{0}
}

func (m *PusherEvent) GetEvent() isPusherEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *PusherEvent) GetClient() *Client {
	if x, ok := x.GetEvent().(*PusherEvent_Client); ok {
		return x.Client
	}
	return nil
}

func (x *PusherEvent) GetServer() *Server {
	if x, ok := x.GetEvent().(*PusherEvent_Server); ok {
		return x.Server
	}
	return nil
}

type isPusherEvent_Event interface {
	isPusherEvent_Event()
}

type PusherEvent_Client struct {
	Client *Client `protobuf:"bytes,1,opt,name=client,proto3,oneof"`
}

type PusherEvent_Server struct {
	Server *Server `protobuf:"bytes,2,opt,name=server,proto3,oneof"`
}

func (*PusherEvent_Client) isPusherEvent_Event() {}

func (*PusherEvent_Server) isPusherEvent_Event() {}

type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToSub string `protobuf:"bytes,1,opt,name=toSub,proto3" json:"toSub,omitempty"`
	Data  []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pusher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_pusher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_pusher_proto_rawDescGZIP(), []int{1}
}

func (x *Client) GetToSub() string {
	if x != nil {
		return x.ToSub
	}
	return ""
}

func (x *Client) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromSub string `protobuf:"bytes,1,opt,name=fromSub,proto3" json:"fromSub,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Server) Reset() {
	*x = Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pusher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_pusher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_pusher_proto_rawDescGZIP(), []int{2}
}

func (x *Server) GetFromSub() string {
	if x != nil {
		return x.FromSub
	}
	return ""
}

func (x *Server) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pusher_proto protoreflect.FileDescriptor

var file_pusher_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a,
	0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22,
	0x32, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x53,
	0x75, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x53, 0x75, 0x62, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x36, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x66, 0x72, 0x6f, 0x6d, 0x53, 0x75, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x66, 0x72, 0x6f, 0x6d, 0x53, 0x75, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x47, 0x0a, 0x06, 0x50,
	0x75, 0x73, 0x68, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x0f, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x42, 0x75, 0x66, 0x66, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pusher_proto_rawDescOnce sync.Once
	file_pusher_proto_rawDescData = file_pusher_proto_rawDesc
)

func file_pusher_proto_rawDescGZIP() []byte {
	file_pusher_proto_rawDescOnce.Do(func() {
		file_pusher_proto_rawDescData = protoimpl.X.CompressGZIP(file_pusher_proto_rawDescData)
	})
	return file_pusher_proto_rawDescData
}

var file_pusher_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pusher_proto_goTypes = []interface{}{
	(*PusherEvent)(nil), // 0: proto.PusherEvent
	(*Client)(nil),      // 1: proto.Client
	(*Server)(nil),      // 2: proto.Server
}
var file_pusher_proto_depIdxs = []int32{
	1, // 0: proto.PusherEvent.client:type_name -> proto.Client
	2, // 1: proto.PusherEvent.server:type_name -> proto.Server
	0, // 2: proto.Pusher.PusherEventBuff:input_type -> proto.PusherEvent
	0, // 3: proto.Pusher.PusherEventBuff:output_type -> proto.PusherEvent
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pusher_proto_init() }
func file_pusher_proto_init() {
	if File_pusher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pusher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PusherEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pusher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pusher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pusher_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PusherEvent_Client)(nil),
		(*PusherEvent_Server)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pusher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pusher_proto_goTypes,
		DependencyIndexes: file_pusher_proto_depIdxs,
		MessageInfos:      file_pusher_proto_msgTypes,
	}.Build()
	File_pusher_proto = out.File
	file_pusher_proto_rawDesc = nil
	file_pusher_proto_goTypes = nil
	file_pusher_proto_depIdxs = nil
}
